apiVersion: v1
kind: Secret
metadata:
  name: novara-db-secret
type: Opaque
stringData:
  # For novara-app
  database-url: "postgresql://novara_user:Admin@2573@postgres-service:5432/novara_db"
  # For postgres deployment
  postgres-user: "novara_user"
  postgres-password: "Admin@2573"